"""Add unique constraint to user email

Revision ID: 6f50c0b389cc
Revises: ade17e833e72
Create Date: 2026-01-16 12:34:10.128456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f50c0b389cc'
down_revision: Union[str, None] = 'ade17e833e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['receiver_id'], ['id'])
    op.drop_column('transactions', 'account_id')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.add_column('transactions', sa.Column('account_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'sender_id')
    # ### end Alembic commands ###
